imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration


framework:
    #esi:             ~
#    translator:      { fallbacks: ["%locale%"] }
    translator:      { fallbacks: [fa] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: snc_redis.session.handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
          cheene_edition_version: "0.1"
          project_name: "%project_name%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        logging:  true
        charset:  UTF8
        mapping_types:
                enum:       string
                set:        string
        types:
                phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Redis configuration
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%redis_default%"
        session:
            type: predis
            alias: session
            dsn: "%redis_session%"
        cache:
            type: predis
            alias: cache
            dsn: "%redis_cache%"
            logging: true
    session:
        client: default
        prefix: %project_name%_sess_
        locking: false
        ttl: 31536000
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache
            entity_manager: [default, read]
            document_manager: [default, slave1, slave2]
            namespace: "dcrc:"
        query_cache:
            client: cache
            entity_manager: default

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Telegram Bot setting
bo_shurik_telegram_bot:
    api:
        token: "%telegram_bot_api_token%"
    name: "%telegram_bot_name%"


# VichUploader Configuration
vich_uploader:
    db_driver: orm
    mappings:
        user_profile_image:
            uri_prefix:         /uploads/images/profile/avatars
            upload_destination: %kernel.root_dir%/../web/uploads/images/profile/avatars
            namer:              vich_uploader.namer_uniqid

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true