backend_route:
    resource: "@CheeneBackendBundle/Resources/config/routing.yml"
    host:     "%panel_domain%"
    prefix:   /
#    schemes:  [https]

frontend_route:
    resource: "@CheeneFrontendBundle/Resources/config/routing.yml"
    host:     "%domain%"
    prefix:   /

cheene_bundle:
    resource: "@CheeneCoreBundle/Resources/config/routing.yml"
    prefix:   /

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_captcha

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

datatable:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation

BoShurikTelegramBotBundle:
    resource: "@BoShurikTelegramBotBundle/Resources/config/routing.yml"
    prefix:   "/_telegram/%telegram_bot_api_token%"
    host:     "%panel_domain%"
