# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        legacy:
            id:  cheene.security.legacy_encoder
        default:
            algorithm: sha512
            encode_as_base64: false
            iterations: 2

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


# http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory: ~
    providers:
            main:
                entity: { class: CheeneUserBundle:User }

    access_decision_manager:
            strategy: unanimous


    firewalls:


        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|telegram|wdt)|css|images|js)/
            security: false

        ## disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(backend|profiler|wdt)|css|images|js)/
            security: false

        ##### Backend
        backend_login:
            pattern: ^/auth/login$
            host:    %panel_domain%
            anonymous: ~

        # secures part of the application
        backend:
            pattern: ^/
            host:    %panel_domain%
            form_login:
                login_path: backend_auth_login
                check_path: backend_auth_login_check
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: backend_auth_logout
                target: backend_auth_login


#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
