<?php

namespace Cheene\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserVerificationTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVerificationTokenRepository extends EntityRepository
{
    public function expireTimeoutTokens()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->update('CheeneUserBundle:UserVerificationToken', 'v')
            ->set('v.expired', ':expired')
            ->where($qb->expr()->lte('v.expiresAt', ':now'))
            ->setParameter('now', new \DateTime())
            ->setParameter('expired', true)
        ;

        $qb->getQuery()->execute();
    }
}
