<?php

namespace Cheene\UserBundle\Entity\Repository;

use Cheene\UserBundle\Entity\User;
use Cheene\UserBundle\Entity\UserForgotPassword;
use Doctrine\ORM\EntityRepository;

/**
 * UserForgotPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserForgotPasswordRepository extends EntityRepository
{
    /**
     * @param $user
     * @return UserForgotPassword
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function hasAlreadyForgetPasswordToken($user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('t')
            ->from('CheeneUserBundle:UserForgotPassword', 't')
            ->where($qb->expr()->andX(
                $qb->expr()->eq('t.user', ':user'),
                $qb->expr()->neq('t.used', ':used'),
                $qb->expr()->neq('t.expired', ':expired')
            ))
            ->setMaxResults(1)
            ->setParameter('user', $user)
            ->setParameter('used', true)
            ->setParameter('expired', true)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return UserForgotPassword
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getActiveToken(User $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('t')
            ->from('CheeneUserBundle:UserForgotPassword', 't')
            ->where($qb->expr()->andX(
                $qb->expr()->eq('t.user', ':user'),
                $qb->expr()->neq('t.used', ':used'),
                $qb->expr()->neq('t.expired', ':expired')
            ))
            ->setMaxResults(1)
            ->setParameter('user', $user)
            ->setParameter('used', true)
            ->setParameter('expired', true)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function expireTimeoutTokens()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->update('CheeneUserBundle:UserForgotPassword', 'u')
            ->set('u.expired', ':expired')
            ->where($qb->expr()->andX(
                $qb->expr()->neq('u.used', ':used'),
                $qb->expr()->neq('u.expired', ':expired'),
                $qb->expr()->lte('u.expiresAt', ':now')
            ))
            ->setParameter('now', new \DateTime())
            ->setParameter('expired', true)
            ->setParameter('used', true)
        ;

        $qb->getQuery()->execute();
    }
}