services:
#    cheene_telegram.example:
#        class: Cheene\TelegramBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.telegram.command.help:
        class: Cheene\TelegramBundle\Command\HelpCommand
        arguments:
            - "@bo_shurik_telegram_bot.command_pool"
        tags:
            - { name: bo_shurik_telegram_bot.command }