services:
    app.telegram.command.help:
        class: AppBundle\Telegram\Command\HelpCommand
        arguments:
            - "@bo_shurik_telegram_bot.command_pool"
        tags:
            - { name: bo_shurik_telegram_bot.command, priority: -512 }

    app.telegram.command.hello:
        class: AppBundle\Telegram\Command\HelloCommand
        tags:
            - { name: bo_shurik_telegram_bot.command }

    app.telegram.command.order:
        class: AppBundle\Telegram\Command\OrderCommand
        arguments:
            - "@app.telegram.order.handler"
            - "@validator"
            - "@event_dispatcher"
        tags:
            - { name: bo_shurik_telegram_bot.command }
